//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVendasWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Fornecedor
    {
        [Key]
        public int COD_FORNECEDOR { get; set; }
        public string NOME_FORNECEDOR { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
    }
}
