//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVendasWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Produto
    {
        [Key]
        public int COD_PRODUTO { get; set; }

        [ForeignKey("fornecedor")]
        public Nullable<int> COD_FORNECEDOR { get; set; }
        public string NOME_PRODUTO { get; set; }
        public Nullable<decimal> PRECO_UNITARIO { get; set; }
    
        public virtual Fornecedor fornecedor { get; set; }
    }
}
