CREATE TABLE PRODUCTS(
PRODUCT_ID    INTEGER,
NAME          VARCHAR(50),
DESCRIPTION   VARCHAR(500),
PRICE         DECIMAL(16,2),
CATEGORY      VARCHAR(50),


PRIMARY KEY (PRODUCT_ID)
);

CREATE SEQUENCE PRODUCTS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;