INSERT INTO PRODUCTS (PRODUCT_ID, NAME, DESCRIPTION, PRICE, CATEGORY) 
VALUES (PRODUCTS_SEQ.NEXTVAL, 'CAMISETA', 'CAMISETA COMUM', 29.95, 'MASCULINA');

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, DESCRIPTION, PRICE, CATEGORY) 
VALUES (PRODUCTS_SEQ.NEXTVAL, 'CHINELO', 'CHINELO RIDER', 49.00, 'MASCULINA');

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, DESCRIPTION, PRICE, CATEGORY) 
VALUES (PRODUCTS_SEQ.NEXTVAL, 'CAMISETA', 'CAMISETA FEMININA FASHION', 99.95, 'FEMININA');

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, DESCRIPTION, PRICE, CATEGORY) 
VALUES (PRODUCTS_SEQ.NEXTVAL, 'CALÇA', 'CALÇA JEANS', 145.00, 'FEMININA');

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, DESCRIPTION, PRICE, CATEGORY) 
VALUES (PRODUCTS_SEQ.NEXTVAL, 'BERM. RAMBO', 'BERMUDA TEMATICA DO RAMBO', 59.99, 'INFANTIL');

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, DESCRIPTION, PRICE, CATEGORY) 
VALUES (PRODUCTS_SEQ.NEXTVAL, 'CAMISA', 'CAMISETA GOLA POLO', 129.95, 'MASCULINA');
